server:
  port: 9000
  servlet:
    context-path: /

spring:
  data:
    redis:
      host: localhost
      port: 6379
#      password: 123456
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-wait: -1ms
          max-active: 16
